server {
    listen       80;
    server_name  localhost;

    root   /usr/share/nginx/html;
    index  index.html;

    # JS y CSS: nunca cachear en el cliente (archivos cambian frecuentemente en demo)
    location ~* \.(js|css)$ {
        add_header Cache-Control "no-store, no-cache, must-revalidate";
        add_header Pragma "no-cache";
        expires -1;
    }

    # HTML: igual, para que el index.html siempre sea fresco
    location ~* \.html$ {
        add_header Cache-Control "no-store, no-cache, must-revalidate";
        add_header Pragma "no-cache";
        expires -1;
    }

    # Resto de assets (imágenes, fonts) — cache normal
    location / {
        try_files $uri $uri/ =404;
    }
}
